[package]
name = "learning-wgpu"
version = "0.1.0"
edition = "2018"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.25"
wgpu = "0.10"
pollster = "0.2"
log = "0.4"
simple_logger = "1.13"
delegate = "0.6"
